### ISSUE TITLE
请教镜像建立后如何启动

### ISSUE THREAD

**Issue by Odimmsun** [zhuweiyou/yiyan-api#4]
您好。我build好镜像后用
`sudo docker run -d --name wxyy-1 -p 3000:80 wxyy`
想启动对应的容器，但是报错如下：
`
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-18T09_05_01_259Z-debug-0.log
`
对docker和JS不懂，求问该怎么解决

**Comment by zhuweiyou** [comment]
你这个报错是有 package.json 文件, 但里面没有 scripts: { start } 这一项, 报的

https://github.com/zhuweiyou/yiyan-api/blob/6f347e48045e46e1133c935644fa116c2224d24c/package.json#L7

但是不应该会报这个, 除非你修改过代码. 拉仓库最新代码, 重新 build 试下

**Comment by Odimmsun** [comment]
@zhuweiyou 感谢回复，容器成功在远程服务器上运行起来了，用的`sudo docker run -d --name wxyy-1 -p 3000:3000 wxyy`启动的容器，现在，在本地电脑上用postman调用接口时报错
```
{
    "message": "Timeout exceeded while waiting for event"
}
```
docker容器显示的日志如下：
```
> yiyan-api@0.0.0 start
> node index.mjs

Listening on http://localhost:3000
TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:153:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:153:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:153:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```
求教这个该怎么解决啊？万分感谢~

**Comment by zhuweiyou** [comment]
不知道是不是网站有更新了，前几天还能用的，晚点有空我看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月18日(周二) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhuweiyou/yiyan-api] 请教镜像建立后如何启动 (Issue #4)




 
@zhuweiyou 感谢回复，容器成功在远程服务器上运行起来了，用的sudo docker run -d --name wxyy-1 -p 3000:3000 wxyy启动的容器，现在，在本地电脑上用postman调用接口时报错
 {     "message": "Timeout exceeded while waiting for event" }  
docker容器显示的日志如下：
 &gt; ***@***.*** start &gt; node index.mjs Listening on http://localhost:3000 TimeoutError: Timeout exceeded while waiting for event     at Timeout.<anonymous&gt; (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:153:28)     at listOnTimeout (node:internal/timers:569:17)     at process.processTimers (node:internal/timers:512:7) TimeoutError: Timeout exceeded while waiting for event     at Timeout.<anonymous&gt; (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:153:28)     at listOnTimeout (node:internal/timers:569:17)     at process.processTimers (node:internal/timers:512:7) TimeoutError: Timeout exceeded while waiting for event     at Timeout.<anonymous&gt; (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:153:28)     at listOnTimeout (node:internal/timers:569:17)     at process.processTimers (node:internal/timers:512:7)  
求教这个该怎么解决啊？万分感谢~

**Comment by zhuweiyou** [comment]
刚调试了一下,一言的网站接口改了, 我刚才修复了,拉取最新代码构建即可

<img width="581" alt="image" src="https://github.com/zhuweiyou/yiyan-api/assets/8413791/381a643a-5980-4b6a-97bd-b20958466c01">

**Comment by Odimmsun** [comment]
@zhuweiyou 大佬，早上还可以，下午好像又不行了，难不成文心的网站又修改接口了？

**Comment by zhuweiyou** [comment]
> @zhuweiyou 大佬，早上还可以，下午好像又不行了，难不成文心的网站又修改接口了？

我看了 确实又改了

**Comment by zhuweiyou** [comment]
已修复
