### ISSUE TITLE
【bug】狠狠得超时了，寄

### ISSUE THREAD

**Issue by Ikaros-521** [zhuweiyou/yiyan-api#6]
```
Listening on http://localhost:3000
TimeoutError: Waiting for selector `#dialogue-input` failed: Waiting failed: 60000ms exceeded
    at Timeout.<anonymous> (file:///D:/GitHub_pro/yiyan-api/node_modules/.store/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/WaitTask.js:68:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by zhuweiyou** [comment]
手动打开网站 <https://yiyan.baidu.com/> 看一眼是什么界面? 
我刚试了是可以的, 可能是你的帐号跳出来别的界面了, 没有考虑到那种情况

**Comment by Ikaros-521** [comment]
> 手动打开网站 <https://yiyan.baidu.com/> 看一眼是什么界面? 
> 我刚试了是可以的, 可能是你的帐号跳出来别的界面了, 没有考虑到那种情况

对哦 是手动开的 直接抓包拿的ck。
我看源码里是playwright吧，没看到打开浏览器，不对头

**Comment by Ikaros-521** [comment]
好吧 不是playwright 0.0
难道是安装失败了。不过也没有报错 也没有打开页面，尴尬

**Comment by zhuweiyou** [comment]
我的意思是你用浏览器打开这个网页，看下是什么页面，我好判断问题。


是安装成功的，从报错看是没有找到输入框。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 凌晨1:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhuweiyou/yiyan-api] 【bug】狠狠得超时了，寄 (Issue #6)




 
好吧 不是playwright 0.0
 难道是安装失败了。不过也没有报错 也没有打开页面，尴尬

**Comment by Ikaros-521** [comment]
难道说是直接给页面注入新内容了吗 那我之后打开截图看看

**Comment by Ikaros-521** [comment]
> 手动打开网站 https://yiyan.baidu.com/ 看一眼是什么界面? 我刚试了是可以的, 可能是你的帐号跳出来别的界面了, 没有考虑到那种情况

![image](https://github.com/zhuweiyou/yiyan-api/assets/40910637/51d7b0c7-950d-4ef9-bde5-fe19d5b49972)

**Comment by Ikaros-521** [comment]
页面看着和原版没有区别
#dialogue-input 确实没有
![image](https://github.com/zhuweiyou/yiyan-api/assets/40910637/a66abb69-22e1-427a-88b1-fe1eb4160c75)

**Comment by zhuweiyou** [comment]
我修复了一版, 用最新代码再试试看

![image](https://github.com/zhuweiyou/yiyan-api/assets/8413791/22a1e8c1-ddb9-4c51-8caf-1a2e7415e738)

**Comment by Ikaros-521** [comment]
> 我修复了一版, 用最新代码再试试看
> 
> ![image](https://github.com/zhuweiyou/yiyan-api/assets/8413791/22a1e8c1-ddb9-4c51-8caf-1a2e7415e738)
> 

感谢大佬 我晚点试试看

**Comment by Ikaros-521** [comment]
有所进展
![image](https://github.com/zhuweiyou/yiyan-api/assets/40910637/04264f45-7409-4e8a-8c9a-5123061590fe)

不过F12 直接弹debug，后面就重定义了，感觉ck就被清了

**Comment by zhuweiyou** [comment]
你这个就是失效了, 或者COOKIE没传对

**Comment by Ikaros-521** [comment]
新获取的ck，但是咋绕过f12检测呢

**Comment by zhuweiyou** [comment]
![image](https://github.com/zhuweiyou/yiyan-api/assets/8413791/6b7ec1ac-37bc-4bcf-a653-e12ba90329ec)

这个界面右键左侧行号, 选择 never pause here ,然后再刷新页面.

应该是你没有获取到关键的那个cookie,到对话界面刷新再获取试试

**Comment by Ikaros-521** [comment]
> ![image](https://user-images.githubusercontent.com/8413791/267273147-6b7ec1ac-37bc-4bcf-a653-e12ba90329ec.png)
> 
> 这个界面右键左侧行号, 选择 never pause here ,然后再刷新页面.
> 
> 应该是你没有获取到关键的那个cookie,到对话界面刷新再获取试试

感谢大佬，成了
